#! /usr/bin/env python

import sys
import prettytable
import pprint

def main():
    columns = []
    for column in sys.stdin.next().split('|'):
        columns.append(column.strip())

    table = prettytable.PrettyTable(columns[1:-1])
    table.align = 'l'
    table.hrules = prettytable.NONE

    for i, line in enumerate(sys.stdin):
        columns = []
        for column in line.split('|'):
            columns.append(column.strip())
        try:
            table.add_row(columns[1:-1])
        except Exception, exc:
            print >> sys.stderr, "%d: %s" % (i, exc)
            return 1

    print table

if __name__ == '__main__':
    sys.exit(main())
